[theme]
base = "dark"
primaryColor = "#FF5733"
backgroundColor = "#110E0E"
secondaryBackgroundColor = "#181212"
textColor = "#F3F4F6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
